module.exports = [
    {
        id: 1,
        title: 'American Idiot',
        artistId: 1,
        albumId: 1,
        youtubeLink: 'h6Z5N0Z6zH0',
        length: '02:54',
        trackNumber: 1,
        lyrics: "Don't want a nation under the new mania And can you hear the sound of hysteria? The subliminal mind-fuck America Welcome to a new kind of tension All across the alien nation Where everything isn't meant to be okay Television dreams of tomorrow We're not the ones who're meant to follow For that's enough to argue Well maybe I'm the faggot America I'm not a part of a redneck agenda Now everybody do the propaganda And sing along to the age of paranoia Welcome to a new kind of tension All across the alien nation Where everything isn't meant to be okay Television dreams of tomorrow We're not the ones who're meant to follow For that's enough to argue Don't wanna be an…",
        playCount: 5,
        likes: 3,
        createdAt: new Date(),
        updatedAt: new Date()
    },
    {
        id: 2,
        title: 'Jesus of Suburbia 1',
        artistId: 1,
        albumId: 1,
        youtubeLink: 'JMcNzjzw63I',
        length: '09:14',
        trackNumber: 2,
        lyrics: "I'm the son of rage and love The Jesus of Suburbia The bible of none of the above On a steady diet of Soda Pop and Ritalin No one ever died for my Sins in hell As far as I can tell At least the ones that I got away with And there's nothing wrong with me This is how I'm supposed to be In a land of make believe That don't believe in me Get my television fix Sitting on my crucifix The living room in my private womb While the Moms and Brads are away To fall in love and fall in debt To alcohol and cigarettes And Mary Jane To keep me insane Doing someone else's cocaine And there's nothing wrong with me This is how I'm supposed to be In a land of make believe That don't believe in me At the center of the earth In the parking lot Of the 7-11 where I was taught The motto was…",
        playCount: 5,
        createdAt: new Date(),
        updatedAt: new Date()
    },
    {
        id: 3,
        title: 'Holiday',
        artistId: 1,
        albumId: 1,
        youtubeLink: 'l2hA8g1cNvQ',
        length: '03:53',
        trackNumber: 3,
        lyrics: "Hear the sound of the falling rain Coming down like an Armageddon flame (hey!) A shame The ones who died without a name Hear the dogs howlin' out of key To a hymn called faith and misery (hey!) And bleed, the company lost the war today I beg to dream and differ from the hollow lies This is the dawning of the rest of our lives On holiday Hear the drum pounding out of time Another protester has crossed the line (hey!) To find, the money's on the other side Can I get another Amen (Amen!) There's a flag wrapped around a score of men (hey!) A gag, A plastic bag on a monument I beg to dream and differ from the hollow lies This is the dawning of the rest of our lives On holiday The representative from California has the floor Sieg Heil to the president gasman Bombs…",
        playCount: 15,
        likes: 3,
        createdAt: new Date(),
        updatedAt: new Date()
    },
    {
        id: 4,
        title: 'Boulevard of Broken Dreams',
        artistId: 1,
        albumId: 1,
        youtubeLink: 'Dx1SPxGn-iU',
        length: '04:21',
        trackNumber: 4,
        lyrics: "I walk a lonely road The only one that I have ever known Don't know where it goes But it's only me, and I walk alone I walk this empty street On the boulevard of broken dreams Where the city sleeps And I'm the only one, and I walk alone I walk alone, I walk alone I walk alone, and I walk a My shadow's only one that walks beside me My shallow heart's the only thing that's beating Sometimes I wish someone out there will find me 'Til then I walk alone Ah ah ah ah ah Ah ah ah I'm walking down the line That divides me somewhere in my mind On the border line of the edge And where I walk alone Read between the lines What's fucked up and every thing's all right Check my vital signs to know I'm still alive And I walk alone I walk alone, I walk alone I walk alone and I walk…",
        playCount: 5,
        createdAt: new Date(),
        updatedAt: new Date()
    },
    {
        id: 5,
        title: 'Are We the Waiting',
        artistId: 1,
        albumId: 1,
        youtubeLink: '6HXa2gVj4mg',
        length: '02:43',
        trackNumber: 5,
        likes: 3,
        lyrics: "Starry nights city lights Coming down over me Skyscrapers, stargazers in my head Are we we are, are we we are The waiting unknown This dirty town was burning down in my dreams Lost and found, city bound in my dreams And screaming Are we we are, are we we are the waiting And screaming Are we we are, are we we are the waiting Forget me nots, second thoughts live in isolation Heads or tails and fairy tales in my mind Are we we are, are we we are the waiting unknown The rage and love, the story of my life The Jesus of suburbia is a lie And…",
        createdAt: new Date(),
        updatedAt: new Date()
    },
    {
        id: 6,
        title: 'St. Jimmy',
        artistId: 1,
        albumId: 1,
        youtubeLink: 'jRu0O1J3Y4s',
        length: '02:55',
        trackNumber: 6,
        lyrics: "St. Jimmy's comin' down across the alleyway Up on the boulevard like a zip gun on parade Light of a silhouette He's insubordinate Coming at you on the count of one, two (one, two, three, four) My name is Jimmy and you better not wear it out Suicide commando that your momma talked about King of the forty thieves And I'm here to represent That needle in the vein of the establishment I'm the patron saint of the denial With an angel face and a taste for suicidal Cigarettes and Ramen and a little bag of dope I am the son of a bitch and Edgar Allan Poe Raised in the city under a halo of lights The product of war and fear that we've been victimized I'm the patron saint of the denial With an angel face and a taste for suicidal Are you talkin' to me? I'll give you…",
        playCount: 11,
        createdAt: new Date(),
        updatedAt: new Date()
    },
    {
        id: 7,
        title: 'Give Me Novacaine',
        artistId: 1,
        albumId: 1,
        youtubeLink: 'ZKAwIwjHwZI',
        length: '03:26',
        trackNumber: 7,
        lyrics: "Take away the sensation inside Bitter sweet migraine in my head It's like a throbbing tooth ache of the mind I can't take this feeling anymore Drain the pressure from the swelling The sensation's overwhelming Give me a long kiss goodnight and everything will be alright Tell me that I won't feel a thing So give me Novacaine Out of body and out of mind Kiss the demons out of my dreams I get the funny feeling, that's alright Jimmy says it's better than here I'll tell you why Drain the pressure from the swelling The sensation's overwhelming Give me a long kiss goodnight and everything will be…",
        playCount: 5,
        likes: 3,
        createdAt: new Date(),
        updatedAt: new Date()
    },
    {
        id: 8,
        title: "She's A Rebel",
        artistId: 1,
        albumId: 1,
        youtubeLink: 'eOv5fF7maFY',
        length: '02:01',
        trackNumber: 8,
        lyrics: "[Chorus] She's a rebel, she's a saint She's the salt of the earth, and she's dangerous She's a rebel, vigilante Missing link on the brink of destruction [Verse 1] From Chicago to Toronto She's the one that they call ol' Whatsername She's a symbol of resistance And she's holding on my heart like a hand grenade [Verse 2] Is she dreaming what I'm thinking? Is she the mother of all bombs? Gonna detonate Is she trouble like I'm trouble? Make it a double twist of fate or a melody that [Bridge] She sings the revolution The dawning of our lives She brings this liberation That I just can't define, well, nothing comes to mind (Hey) [Guitar Solo]",
        playCount: 5,
        createdAt: new Date(),
        updatedAt: new Date()
    },
    {
        id: 9,
        title: 'Extraordinary Girl',
        artistId: 1,
        albumId: 1,
        youtubeLink: 'hctq2W1z7Kc',
        length: '03:34',
        trackNumber: 9,
        lyrics: "She's an extraordinary girl In an ordinary world And she can't seem to get away He lacks the courage in his mind Like a child left behind Like a pet left in the rain She's all alone again Wiping the tears from her eyes Some days he feels like dying She gets so sick of crying She sees the mirror of herself And image she wants to sell To anyone willing to buy He steals the image in her kiss From her hearts apocalypse From the one called what's her name She's all alone again Wiping the tears from her eyes Some days she feels like dying She gets so sick of crying She's all alone…",
        playCount: 2,
        likes: 3,
        createdAt: new Date(),
        updatedAt: new Date()
    },
    {
        id: 10,
        title: 'Letterbomb',
        artistId: 1,
        albumId: 1,
        youtubeLink: '1fi-MLyBfB0',
        length: '04:06',
        trackNumber: 10,
        lyrics: "Nobody likes you Everyone left you They're all out without you Having fun Where have all the bastards gone? The underbelly stacks up ten high The dummy failed the crash test Collecting unemployment checks Like a flunkie along for the ride Where have all the riots gone? As your city's motto gets pulverized What's in love is now in debt On your birth certificate So strike the fucking match to light this fuse The town bishop is an extortionist And he don't even know that you exist Standing still when it's do or die You better run for your fucking life It's not over 'till you're underground It's not over before it's too late This city's burnin' It's not my burden It's not over before it's too late There's nothing left to analyze Where will all the martyrs go when the…",
        createdAt: new Date(),
        updatedAt: new Date()
    },
    {
        id: 11,
        title: 'Wake Me Up When September Ends',
        artistId: 1,
        albumId: 1,
        youtubeLink: 'imfEO_rjpU4',
        length: '04:46',
        trackNumber: 11,
        likes: 3,
        lyrics: "Summer has come and passed The innocent can never last Wake me up when September ends Like my fathers come to pass Seven years has gone so fast Wake me up when September ends Here comes the rain again Falling from the stars Drenched in my pain again Becoming who we are As my memory rests But never forgets what I lost Wake me up when September ends Summer has come and passed The innocent can never last Wake me up when September ends Ring out the bells again Like we did when spring began Wake me up when September ends Here comes the rain again Falling from the stars Drenched in my pain again Becoming who we are As my memory rests But never forgets…",
        createdAt: new Date(),
        updatedAt: new Date()
    },
    {
        id: 12,
        title: 'Homecoming',
        artistId: 1,
        albumId: 1,
        youtubeLink: '58hUq7hnueQ',
        length: '09:18',
        trackNumber: 12,
        lyrics: "My heart is beating from me I am standing all alone Please call me only if you are coming home Waste another year flies by Waste a night or two You taught me how to live In the streets of shame Where you've lost your dreams in the rain There's no signs of hope The stems and seeds of the last of the dope There's a glow of light The Saint Jimmy is the spark in the night Bearing gifts and trust The fixture in the city of lust What the hell's your name? What's your pleasure and what is your pain? Do you dream too much? Do you think what you need is a crutch? In the crowd of pain Saint Jimmy comes without any shame He says, 'We're fucked up' and we're not the same And mom and dad are the ones you can blame Jimmy died today He blew his brains out into the bay In this…",
        createdAt: new Date(),
        updatedAt: new Date()
    },
    {
        id: 13,
        title: 'Whatsername',
        artistId: 1,
        albumId: 1,
        youtubeLink: 'Z2LC1xrdOaM',
        length: '04:12',
        trackNumber: 13,
        likes: 3,
        lyrics: "Thought I ran into you down on the street Then it turned out to only be a dream I made a point to burn all of the photographs She went away and then I took a different path I remember the face But I can't recall the name Now I wonder how whatsername has been Seems that she disappeared without a trace Did she ever marry old what's his face I made a point to burn all of the photographs She went away and then I took a different path I remember the face But I can't recall the name Now I wonder how whatsername has been Remember, whatever It seems like forever to go Remember, whatever It seems…",
        createdAt: new Date(),
        updatedAt: new Date()
    },
    {
        id: 14,
        title: 'Wake',
        artistId: 2,
        albumId: 2,
        youtubeLink: 'Me7TJDHCELk',
        length: '01:41',
        trackNumber: 1,
        lyrics: " Should I have a taste of thisStart and crush your nailsAnd start all over againCould this all just be a dreamIf I should fall to stormy weatherWake Me, Wake MeyeahMaybe this time I can do it all wrongWithout my foot in my mouthWithout that blind in my sightCould this all just be a dreamIf i should fall…",
        createdAt: new Date(),
        updatedAt: new Date()
    },
    {
        id: 15,
        title: 'Given Up',
        artistId: 2,
        albumId: 2,
        youtubeLink: '0xyxtzD54rM',
        length: '03:11',
        trackNumber: 2,
        lyrics: "Wake in a sweat again Another day's been laid to waste In my disgrace Stuck in my head again Feels like I'll never leave this place There's no escape I'm my own worst enemy I've given up I'm sick of feeling Is there nothing you can say? Take this all away I'm suffocating Tell me what the fuck is wrong with me? I don't know what to take Thought I was focused but I'm scared I'm not prepared I hyperventilate Looking for help somehow somewhere And no one cares I'm my own worst enemy I've given up I'm sick of feeling Is there nothing you can say? Take this all away I'm suffocating Tell me what the fuck is wrong with me? God! Put me out of my misery Put me out of my misery Put me out of my— Put me out of my fucking misery I've given up I'm sick of feeling Is there nothing you can say? Take this all away I'm suffocating Tell me what the fuck is wrong with me?",
        playCount: 5,
        likes: 3,
        createdAt: new Date(),
        updatedAt: new Date()
    },
    {
        id: 16,
        title: 'אם רק היית יודעת',
        artistId: 4,
        albumId: 4,
        youtubeLink: 'gg-Aby8eE1M',
        length: '03:38',
        trackNumber: 1,
        lyrics: "המחשבות הורגות אותי קבוע קשה לשתוק לא מתרגל לאחרונה כל יום מרגיש שבוע הכל שטויות טוב תלוי מי שואל אולי תגידי מה עובר עלי רק תגידי שהכל בסדר קצת הרגיש לי שגדול עלי אולי אם רק היית יודעת איך המילים שלך עושות אותי רגוע ואני יותר סגור את עם השטויות שלך הרבה יותר בטוח ואני שוב משתגע איך זה בא בזמן  זה הרבה יותר עדיף לא להיות מוכן המנגינות באות צריך לנוע קשה לרקוד לא מסתכל הרכבות עוברות ואני תקוע לאן כולם נוסעים כאן לעזאזל אולי תגידי לי מילים טובות אולי תצאי קצת מהחדר אולי ירדו לך עוד כמה דמעות אולי כדאי אם רק היית יודעת איך המילים שלך עושות אותי רגוע ואני יותר סגור את עם השטויות שלך הרבה יותר בטוח ואני שוב משתגע איך זה בא בזמן זה הרבה יותר עדיף לא להיות מוכן ",
        playCount: 5,
        createdAt: new Date(),
        updatedAt: new Date()
    },
    {
        id: 17,
        title: 'שומרים אהבה',
        artistId: 4,
        albumId: 4,
        youtubeLink: 'lMVun_6B5TU',
        length: '02:47',
        trackNumber: 2,
        likes: 3,
        lyrics: "שלוש בלילה לא נרדם יוצא לשתות קפה סיגריה כולם ישנים הבטן מתהפכת מאתמול בערב חברים אומרים שזה פרפרים ואת וודאי כבר ישנה מתחת לשמיכה מחבקת דובי גדול שלושה וחצי קילומטרים מפרידים בנינו רק תבואי עכשיו בלי לשאול אני רואה לך בעיניים הדבר הכי יפה נשבע שאת הכי יפה מכולן בואי ניסע לנו שיקגו פריז או ברצלונה כל מקום שתבחרי בעולם רק גיטרה ישנה והחיוך שלך נצחק בכל הרחובות שכולם ישמעו אותנו עכשיו החברות שלך כבר מבינות על מה פה מדברים שומרים אהבה אז את צוחקת קוראת את תסמס שלי מראה אותו לכולם תמד פחדת להתקרב אבל בחרת אותי כי יש לך טעם מושלם רק אני ואת רחוק מכל האנשים על אי בודד שמיים נקיים ים כחול ניסע בינתיים שנה שנתיים יום יומיים רק תבואי עכשיו בלי לשאול",
        createdAt: new Date(),
        updatedAt: new Date()
    },
    {
        id: 18,
        title: 'אוסף עוד געגוע',
        artistId: 4,
        albumId: 4,
        youtubeLink: 'fDOVhjbJ8fg',
        length: '03:43',
        trackNumber: 3,
        lyrics: "כל העיר כבר מדברים שאת לא כאן מספרים שאת הלכת לעיר אחרת ורק אני מדבר לשקט  מספר לו כמה שאת חסרה לי ואמא כל הזמן אומרת תהיה חזק תבוא אחת שתרים אותך גבוה היא תרפא לך את הכאב תלטף לך את הלב בסוף תצחק על הכאב אז תגידי איך בלילות אני מדבר עם הלבד אומרים שאהבה היא לא ליום אחד אז תחזרי כי לא הולך לי כלום גם כשניסיתי לקום  נפלתי שוב אלייך אז תגידי איך בסוף תמיד חוזרים להתחלה אומרים שאהבה היא התרופה אז תחזרי כי לא הולך לי כלום גם כשניסיתי לקום, נפלתי שוב אלייך כל הבגדים שאת השארת זרוקים בחדר תמונות שלך על קיר ישן מספרות הכל עוד דקה כמעט שבור  אוסף עוד געגוע עד שתחזרי אז תגידי איך בלילות אני מדבר עם הלבד אומרים שאהבה היא לא ליום אחד אז תחזרי כי לא הולך לי כלום גם כשניסיתי לקום  נפלתי שוב אלייך אז תגידי איך בסוף תמיד חוזרים להתחלה אומרים שאהבה היא התרופה אז תחזרי כי לא הולך לי כלום גם כשניסיתי לקום, נפלתי שוב אלייך אז תגידי איך בלילות אני מדבר עם הלבד אומרים שאהבה היא לא ליום אחד אז תחזרי כי לא הולך לי כלום גם כשניסיתי לקום  נפלתי שוב אלייך אז תגידי איך בסוף תמיד חוזרים להתחלה אומרים שאהבה היא התרופה אז תחזרי כי לא הולך לי כלום גם כשניסיתי לקום, נפלתי שוב אלייך",
        createdAt: new Date(),
        updatedAt: new Date()
    },
    {
        id: 19,
        title: 'מכאן ועד הנצח',
        artistId: 4,
        albumId: 4,
        youtubeLink: 'NwDvbCkwGXo',
        length: '04:00',
        trackNumber: 4,
        likes: 3,
        lyrics: "אחרי הכל תראי אותנו  איך שניצחנו ביחד את כל הקשיים   את הסיבה שיש לי שקט  כשאת צוחקת  כל כך רגוע לי בפנים   איתך מכאן ועד הנצח  בים של אושר  את צבעת את עולמי  ורק איתך אני זורח את כמו חלום  מתגשם כאן למולי מבטיח לך לשמור עלינו  כמו על העיניים  הירוקות שלך איך באת לי משמיים  תראי אנחנו שניים כאן אוחזים ידיים אני אלך איתך באש וגם במים יחד מול כולם",
        createdAt: new Date(),
        updatedAt: new Date()
    },
    {
        id: 20,
        title: 'מכל האהבות הזמניות',
        artistId: 4,
        albumId: 4,
        youtubeLink: 'cNbosdY6skw',
        length: '03:48',
        trackNumber: 5,
        lyrics: "מכל האהבות הזמניות  ניצחת לי את הזמן ואת הנצח  אחרי כל הנפילות והכוויות נפתח לי המזל את המפתח עכשיו שוב נסחפים  כמו גלים קטנים אל חוף מבטחים  לא חשוב לי מה אומרים  עלינו  את כמו השמש לב של זהב את כל התפילות שכיוונתי עכשיו האור שחסר לי כל השנים  אתן לך את כל החיים אתן את הכל ואפילו יותר  אתן את עצמי וזה לא יגמר מתי מתי תביני שאת כל חיי מכל האהבות הזמניות  מצאתי אהבה שתנצח  אחרי כל השנים והדמעות הגעת לחיי כמו אור ירח עכשיו שוב נסחפים כמו גלים קטנים אל חוף מבטחים לא חשוב לי מה אומרים  עלינו  אתה כמו השמש לב של זהב   כל התפילות שכיוונתי עכשיו  האור שחסר לי כל השנים  אתן לך את החיים אתן את הכל אפילו יותר אתן את עצמי וזה לא יגמר מתי מתי תבין שאתה כל חיי",
        createdAt: new Date(),
        updatedAt: new Date()
    },
    {
        id: 21,
        title: 'עושה עם העיניים',
        artistId: 4,
        albumId: 4,
        youtubeLink: '16-W0TnRE84',
        length: '02:55',
        trackNumber: 6,
        likes: 3,
        lyrics: "כמה מילים חסרות,גם מבט משתיקות אי אפשר להרכיב  עושה לי דמעות, נשבע שבכלל לא תכננתי לריב כמה צעקות על הרצפה שאת לא אוספתשוב אני יושב על הספה שכבר ראתה הכל איך מחייכת בשניה עושה מה לא עושה עם העיניים והגוף שלך מושיט ידייםמחבקת ובוכה עושה מה לא עושה אני עדיין אביא לך, כמה שאני אביא לך כל מה שתרצי אשיר לך אשאיר לך את עצמי בינתיים אם לא סופרים ת׳לילות את עדיין אוכלת את כל השטויות מי מכיר אחרות וזה שלא אהבנו לרגע פחות שנינו מביטים על התקרה,ואת לא אומרת אף פעם לא הבנתי מה קרה זה לא שאני יכול איך מחייכת בשניה עושה מה לא עושה עם העיניים והגוף שלך מושיט ידייםמחבקת ובוכה עושה מה לא עושה אני עדיין אביא לך, כמה שאני אביא לך כל מה שתרצי אשיר לך אשאיר לך את עצמי בינתייםאת מחייכת בשניה עושה מה לא עושה עם העיניים והגוף שלך מושיט ידייםמחבקת ובוכה עושה מה לא עושה אני עדיין אביא לך, כמה שאני אביא לך כל מה שתרצי אשיר לך אשאיר לך את עצמי בינתיים",
        playCount: 10,
        createdAt: new Date(),
        updatedAt: new Date()
    },
    {
        id: 22,
        title: 'רכבת הרים',
        artistId: 4,
        albumId: 4,
        youtubeLink: 'eiRP_H_me1Q',
        length: '02:49',
        trackNumber: 7,
        lyrics: "מאמי מה קרה לי עכשיו את חסרה לי חשבתי שגמרנו מזמן אני לא יודע איך אחרי חודשיים מצאת אותי בינתיים הלב שלי גם ככה ישן אני לא יודע שום דבר אנלא  יודע שום דבר והימים עוברים לי לאט ומי אני בכלל אם לא את בלילה בשמיכה בבוקר בזריחה הלב שלי רכבת הרים בעיר הזאת בין כל השבורים אני מקום ראשון אנלא הולך לישון הלילה מאמי זה כואב שנים אני סוחב אותך איתי לכל מקום אני לא יודע אם את מאושרת עכשיו כשאת חוזרת אליו הביתה בסוף יום",
        createdAt: new Date(),
        updatedAt: new Date()
    },
    {
        id: 23,
        title: 'קרובה אליי',
        artistId: 4,
        albumId: 4,
        youtubeLink: 'hd0-ErzWynU',
        length: '03:24',
        trackNumber: 8,
        likes: 3,
        lyrics: "על כביש מהיר בדרך, חיוך על הפנים  הרוח שנושבת, החלונות פתוחים ברדיו משמיעים עוד איזה שיר  על אהבה מדברים... ואת כמו משוגעת, צועקת תמילים  אני מצטרף ואז אנחנו צוחקים  איך אני אוהב את השטויות  שאנחנו עושים ואם תרגישי עצובה, אני אבוא ואחבק את כל פחדייך אסלק עינייך מול עיניי  שפתייך אל שפתיי  כל כך קרובה אליי  הלב דופק משתגע  שלא יגמר הרגע לעולם  כל כך הרבה שנים  עברו חיים שלמים  תקופות קשות שרק אלוהים שומע  ננצח כל צבא שבעולם  ורק אני מכיר את השריטות שלך,  מה את הכי אוהבת, מה קצת מעצבן אותך, כמה שנריב בסוף היום הכל נשכח ונסלח וכשמגיע לילה נכנסים אל המיטה, היום הולך להיגמר ממש בעוד דקה, את מרימה תראש אני גונב.... ממך נשיקה. ואם תרגישי עצובה, אני אבוא ואחבק את כל פחדייך אסלק",
        createdAt: new Date(),
        updatedAt: new Date()
    },
    {
        id: 24,
        title: 'חוזר הביתה',
        artistId: 4,
        albumId: 4,
        youtubeLink: 'b5tDzaud0aA',
        length: '03:16',
        trackNumber: 9,
        lyrics: "אמא לך אני מבטיח לשבת אחזור זה החייל שלך אני כל כך מתגעגע אמא רק אל תדאגי אני פה לא לבד כולם פה זה אחד ואת איתי אני יודע ובלילות קרים תופר שמירות לבד ואת נמצאת תמיד בתוך הנשמה שלי תרגיעי גם את אבא רק שלא יפחד אל תשכחי גם לנשק את אחותי גם כשמסתער קדימה את איתי יאמא את האור במקומות חשוכים כשמפחיד בלילה מסתכל למעלה בשבילי את כמו מיליון כוכבים אוהב אותך אמא עוד כמה ימים אני חוזר הביתה איך אני מתגעגע לריחות שבת לגנוב מהסירים, שיחות קטנות על המרפסת איך אני כבר מת לפשוט את המדים אמבטיה, מנוחה ואז עם סבא לבית כנסת אולי אנלא אומר מספיק אוהב אותך אבל מרגיש אותך בתוך הנשמה שלי ומתפלל לאל רק שישמור עלי שאוכל לחזור אליך אל ביתי",
        createdAt: new Date(),
        updatedAt: new Date()
    },
    {
        id: 25,
        title: 'רק לעוד דקה',
        artistId: 4,
        albumId: 4,
        youtubeLink: 'ZxPIADYOYoI',
        length: '03:21',
        trackNumber: 10,
        likes: 3,
        lyrics: "לא מבין איך את כך מתרחקת כל חיי הפכו פתאום לשקט לעזוב הכל איך את כך יכולה כשאני עוד לא מבין מה קרה בלילות שיכור השארת לי רק כאב רחובות קרים הראש כבר מסתובב לא נתת לי להסביר גם לא מילה חיים שלמים ארזת איתך במזוודה אל תאמרי שאת עוזבת אל תאמרי כבר לא אוהבת שבנינו כל הרגש נעלם תני סיכוי קטן לשנינו לא אל תוותרי עלינו בואי נשב אפילו רק לעוד דקה איך הזיכרונות עולים צפים עכשיו זוכרת שהבטחנו שתמיד נאהב ואם את רוצה לחזור בחזרה בואי נשכח ושוב נתחיל מהתחלה",
        createdAt: new Date(),
        updatedAt: new Date()
    },
    {
        id: 26,
        title: 'לעשות איתך שלום',
        artistId: 4,
        albumId: 4,
        youtubeLink: '9PTH36lPuzg',
        length: '03:28',
        trackNumber: 11,
        lyrics: "דיברנו שעות בשקט נשארתי ואת הולכת איתך אי אפשר אחרת איך אני לבד תגידי שאת בסדר שעוד לא מצאת לך גבר סגור כמו אידיוט בחדר איך אני לבד אז מה עושים עם כל הרעש שלא לקחת איתך היום כבר לא מוכרים פה שקט רק זורקים לפח תני לי לעשות איתך שלום תדברי איתי אני חוזרת עוד היום רק תגידי לי אני כבר מחכה ליד הדלת תני לי לעשות איתך הכל תסתכלי עלי אני כבר לא פוחד ליפול תנסי אולי זה לא יפה לנו לבד אז מה עם הגעגוע עבר כבר כמעט שבוע באמא אנלא רגוע איך אני לבד שמעתי שאת נשברת כמוני את עוד אוהבת תגידי לי מה את אומרת איך אני לבד אז מה עושים עם כל הכעס שלא לקחת איתך היום כבר לא מוכרים פה רגש רק זורקים לפח",
        createdAt: new Date(),
        updatedAt: new Date()
    },
    {
        id: 27,
        title: 'עומד כאן לבדי',
        artistId: 4,
        albumId: 4,
        youtubeLink: 'CoH5kL1CgRA',
        length: '03:44',
        trackNumber: 12,
        lyrics: "מולך בורא עולם אני עומד כאן לבדי נושא עיניי אל השמיים בקול שבור מודה אני לך קוני אין עוד מלבדך אתה יוצר בשר ודם אתה מנהיג ברחמייך אתה מלך העולם לך כולם כבן סורר הייתי שלא הלך בדרכך אני טעיתי אבל צמאה נפשי אליך לבקש סליחה כי אין בי כלום בלי תורתך אלוקים שלי רק רציתי שתדע שלמרות שנפלתי אני קם עם חיוך ובליבי עוד נושא תפילה אבאלה שלי אני קורא לך אבאלה שלי תגלה רחמיך על כל עמיך ישראל, אהוביך אב הרחמן לך מודים כל הבריות עושה שמיים וארץ אתה אדיר בנפלאות, אל נחמות אין עוד מלבדך אתה יוצר בשם ודם אתה מנהיג ברחמיך אתה מלך העולם לך כולם כבן סורר הייתי שלא הלך בדרכך אני טעיתי אבל צמאה נפשי אליך לבקש סליחה כי אין בי כלום בלי תורתך",
        createdAt: new Date(),
        updatedAt: new Date()
    },
    {
        id: 28,
        title: 'אסטה מניינה',
        artistId: 5,
        albumId: 5,
        youtubeLink: '-hu2uQ5xKrA',
        length: '03:37',
        trackNumber: 1,
        lyrics: "בעוד רגע ניפרד ונעלם בתוך עשן המסך פתאום ירד כמו בתיאטרון ישן גם הסוף הוא לפעמים התחלה של משהו טוב ואם אוהבים אז ניפגש בקרוב הדמעות על לחיי הם מעצב ושמחה את הכל אתה בוחר אבל לא משפחה העולם בחוץ קורא לי ללגום את החיים בטרם אנחנו עכשיו נפרדים נשאר חבוקים עוד כמה רגעים אסטה מניינה אסטה מניינה אם החיים הם כמו נהר ודאי ניפגש כאן גם מחר אסטה מניינה אסטה מניינה בין הגלים והסירות יש מגדלור שמחכה לי בלילות חלומות וזיכרונות שאשא בתרמילי מה יביא לו המחר ומה צופן לו גורלי יש לי שיר יש לי גיטרה ורוח בכנפי ילכו הם אתי בכל צעדי ישאו את קולי ואת תפילותי אסטה מניינה אסטה מניינה אם החיים הם כמו נהר ודאי ניפגש כאן גם מחר אסטה מניינה אסטה מניינה בין הגלים והסירות יש מגדלור שמחכה לי בלילות",
        createdAt: new Date(),
        updatedAt: new Date()
    },
    {
        id: 29,
        title: 'שריקות',
        artistId: 5,
        albumId: 5,
        youtubeLink: 'stVA7Krjj1c',
        length: '03:10',
        trackNumber: 2,
        lyrics: "תגידי רק איך קוראים לך ולמה את הולכת כאן לבד השעה מאוחרת מסוכן בואי אלווה אותך ואם קר יש לי אוטו על המושבים כיסוי פרווה כלבלב מנענע את הראש שלו מצד לצד נו למה את בורחת אני נותן את לא לוקחת מאף אחד מאף אחד תגידי שנמאס לך משריקות ותנועות מוזרות עם הידיים תגידי שנמאס לך ממילים שבקלות נמחקות במים ואם לא יבוא אחד שישחק לך בנשמה תישארי לבד הוא לא שואל וכבר מזמין לך עוד פינה קולדה מהבר הדיבור שלו מזכיר לך את ההוא מהשבוע שעבר נו למה את בורחת אני נותן את לא לוקחת מאף אחד מאף אחד",
        createdAt: new Date(),
        updatedAt: new Date()
    },
    {
        id: 30,
        title: 'האהבה שלך ניצחה',
        artistId: 5,
        albumId: 5,
        youtubeLink: 'vz5yqORGf8M',
        length: '03:50',
        trackNumber: 3,
        likes: 3,
        lyrics: "הייתה תקופה קשה התלבטות בינך לבינה הלב שלי נדם שעות הראש במחשבות חשבתי זה נגמר בדרכי לאהבה חדשה אך בתוכי ידעתי אני שלך לא ויתרת על שנינו האהבה שלך ניצחה אני ידעתי לבית חם פינה בלב חזרתי אומר תודה לאל שלא עזבתי סלחי לי אהובה דמעה ועוד דמעה איך ביקשתי אותך חזרה רציתי שנאהב לעד שתבואי ותושיטי יד מצטער שלא ניסיתי ואיתך אני טעיתי אך בתוכי ידעתי אני שלך לא אוותר על שנינו",
        createdAt: new Date(),
        updatedAt: new Date()
    },
    {
        id: 31,
        title: 'כוסית של יין',
        artistId: 5,
        albumId: 5,
        youtubeLink: 'dp3V29rpvX4',
        length: '03:34',
        trackNumber: 4,
        lyrics: "קח כוסית של יין למחשבות טובות אל תרים ידיים וצא רק לבלות קום כבר בן אדם עוף על העולם יש בך הכוח קום ואל תישן כשהמזל בורח והחיים קשים אחוז באמונה שיקרו דברים טובים תאמין בעצמך אפשר עוד לשנות אל תישבר ותתגבר כי יש ממה לחיות קח כוסית של יין למחשבות טובות אל תרים ידיים וצא רק לבלות קום כבר בן אדם עוף על העולם יש בך הכוח קום ואל תישן אם אתה שוקע והזמן עוצר הרם ראשך למעלה ותדבר תאמין בעצמיך ואל תישבר תן חיוך ולטובה הכל כבר יסתדר",
        createdAt: new Date(),
        updatedAt: new Date()
    },
    {
        id: 32,
        title: 'בשעות המתות',
        artistId: 5,
        albumId: 5,
        youtubeLink: 'K4tOrliXqWA',
        length: '03:38',
        trackNumber: 5,
        lyrics: "עברת לגור בפינה של המדינה מודה שניסיתי להבין מה זה אומר אם ניפגש שוב ברחוב בלי כוונה עם הלב יפול לך מבלי להישבר אפשר ממש לספור נשימה נשימה בדיוק מהרגע שיצאת לי מהדלת שלא תחשבי שקל לי בכוחות עצמי לדמיין כל יום גשום איתך בסמיכות בין הקירות כשהיית אז מתפשטת למולי זמן שהלכתי לאיבוד בשעות המתות החזאים כבר לא מצליחים לדייק אני ממשיך להירטב בזיכרונות הסבלנות שלי עומדת כבר להיגמר במחול הזה על רצפה מזכוכיות אפשר ממש לספור נשימה נשימה בדיוק מהרגע שיצאת לי מהדלת",
        createdAt: new Date(),
        updatedAt: new Date()
    },
    {
        id: 33,
        title: 'זמן לאהבה',
        artistId: 5,
        albumId: 5,
        youtubeLink: 'MA0-ge7z0o0',
        length: '03:27',
        trackNumber: 6,
        lyrics: "אומרים שסוף הקיץ זמן לאהבה אז איך עוד לא מצאתי לי אותך אני לא יודע אומרים לי כל החברה התחתנו מזמן ורק אני נשארתי לי לבד אותי זה משגע למה תגידו לי למה זה כל כך קשה וכמה אני אמשיך עוד לחכות עד שתבוא אלי ותחמם לי את הלב טיפות קטנות של גשם ישתפו את הכאב כשהיא תבוא אלי כל העצב יסתלק אזמין אותה לחדר לעוד ריקוד סוער הלילה אך איזה לילה התנור דולק בוער לחורף חם שוב מתפלל כולם אומרים שחורף זמן לאהבה ורק אצלה אמצא את התרופה כן אני יודע , אומרים לי שכל עכבה זה לטובה אבל הראש שלי כבר מתפוצץ מלחשוב עליה למה תגידו לי למה זה כל כך קשה וכמה אני אמשיך עוד לחכות",
        createdAt: new Date(),
        updatedAt: new Date()
    },
    {
        id: 34,
        title: 'לאט',
        artistId: 5,
        albumId: 5,
        youtubeLink: 'EFBIK_sJewA',
        length: '03:34',
        trackNumber: 7,
        lyrics: "זו מין תקופה כזאת שום דבר כאן לא ידוע שוב משקרים בחדשות על מלחמה ואת אומרת זה מפחיד פחות כשאתה בבית כולם כאן מכוונים אך אף אחד כבר לא פוגע משוגעים שרק רודפים אחרי עצמם כשהם רצים רק את יודעת לעצור לי את הזמן לאט לאט חיים שלי אתה אוהב כשהיא קצת משקרת תצחק ותפתה אותי אך אל תשכח לומר לי כשאני נופלת לאט לאט חיים שלי אתה אוהב כשהיא קצת משקרת תצחק ותפתה אותי זה עושה אותי מאושרת זה העולם וגם אנחנו תחנות של רוח מנסים להילחם על שום דבר כולם רצים מהר מדי לא מדברים על אהבה כולם רצים מהר וכבר לא מדברים על אהבה",
        createdAt: new Date(),
        updatedAt: new Date()
    },
    {
        id: 35,
        title: 'בוקר יום ראשון',
        artistId: 5,
        albumId: 5,
        youtubeLink: 'JJAivtYGkAk',
        length: '03:57',
        trackNumber: 8,
        lyrics: "בוקר יום ראשון כבר שעה שאני תקוע בפקק על כביש באיילון התנועה זורמת לאט פותח את הרדיו מדינה בהמתנה התקשרתי פעמיים את בטח ישנה מסמס לך בינתיים לבבות בתוך תמונה תמיד לאן שאלך אליך אחזור חכי לי מעט אל תכבי את האור חוזר שוב הביתה על הדלת כתוב גרים כאן בכיף עוד רגע נשוב לאן שאלך אליך אחזור חכי לי מעט אל תכבי את האור חוזר שוב הביתה אני שוב לצידך יותר לא אלך בוקר יום ראשון אני עוצר לקפה בקטנה פותח ת'עיתון בנפאל רעידת אדמה צלצול קטן לפתע על הצג תמונה שלך שטיילנו אז ביפו כשהכרתי אותך שיהיה לך יום שמח נשיקות שלחתי לך אם אלך אליך אחזור חכי לי מעט אל תכבי את האור חוזר שוב הביתה על הדלת כתוב גרים כאן בכייף עוד רגע נשוב תמיד לאן שאלך אליך אחזור חכי לי מעט אל תכבי את האור חוזר שוב הביתה אני שוב לצידך אני שוב לצידך יותר לא אלך",
        createdAt: new Date(),
        updatedAt: new Date()
    },
    {
        id: 36,
        title: 'כל העיר יודעת',
        artistId: 5,
        albumId: 5,
        youtubeLink: 'vNViGyjZpq0',
        length: '03:33',
        trackNumber: 9,
        likes: 3,
        lyrics: "איך הבאנו את עצמנו למצב הזה אני כבר לא מוצא  ולפעמים את שם פותחת דלת לא חלמתי שנגיע עד הקצה אני עוד מקווה שבלילות שלך את עליי חולמת בגלל הרוח אין לי מצב רוח שוב לחייך  לאן אלך כבר כל העיר יודעת ששברת לי את הלב איבדתי את הדעת ושילמתי בכאב על הכבישים נוסע הכי רחוק ממך  כולי כבר משתגע ברחובות על שמך וכל זה בגללך עם מי את צוחקת כל הזמן תוהה עם הדמיון הוזה כיוון נכון מכאן ללכת  הגורל נקבע גם בלי שנרצה אני עכשיו חוצה את שבילי חיי בלי רגע שקט בגלל הרוח אין לי מצב רוח שוב לחייך לאן אלך כבר כל העיר יודעת ששברת לי את הלב איבדתי את הדעת ושילמתי בכאב על הכבישים נוסע הכי רחוק ממך  כולי כבר משתגע ברחובות על שמך וכל זה בגללך",
        createdAt: new Date(),
        updatedAt: new Date()
    },
    {
        id: 37,
        title: 'יום שני',
        artistId: 5,
        albumId: 5,
        youtubeLink: '16i44IJSnc8',
        length: '03:53',
        trackNumber: 10,
        lyrics: "יום שני בלילה טלפון מקרלה  בוא אליי מהר איך היא שוב לוחשת דרינק קטן וסרט ואז תישאר מניע את האוטו עוד רמזור אחד ימינה וחונה דופק בדלת היא פותחת יום שלישי בלילה טלפון מלילה  מה קורה איתך שוב משעמם לי מה אתה אומר אולי תיתן קפיצה מניע את האוטו עוד סיבוב פרסה ימינה וחונה  דופק בדלת היא פותחת יום שישי קופץ לרינה  הראש שלי אצל דינה רינה  מי זאת גרה בראש פינה יום שבת חוזר לאמא משם חותך כבר לסימה סימה ואז לפוקר אצל דימה איך זה שוב קורה לי עם כל הבאלאגן הזה לא מאושר מה אני עושה איך אני יוצא מזה עוד לא מאוחר ומה תגיד לי מה יהיה מחר ראשון בצהריים שמש בעיניים עם קרין בלאנצ׳ טלפון מסוזי בא לך גקוזי איזה בלאגאן  מניע את האוטו עוד פנייה חדה ימינה וחונה דופק בדלת היא פותחת",
        createdAt: new Date(),
        updatedAt: new Date()
    },
    {
        id: 38,
        title: 'על סף ביתך',
        artistId: 5,
        albumId: 5,
        youtubeLink: '7vc6maGiR2U',
        length: '03:38',
        trackNumber: 11,
        lyrics: "לפעמים זו האמת לא נשאר לי מה לתת מחפש עוד רסיסים של היגיון איך מולך תמיד נשבר מאבד את המחר איך הבטחת לי שאהיה אצלך ראשון כבר שנים איני צוחק מתקרב ומתרחק מה יהיה בסוף אין איש יודע שוב אני על סף ביתך מתחנן למבטך לא הצלחתי לאהוב אחת אחרת הסודות הפכו גלויים הלילות רדפו ימים כשעולה האור רק את נשארת לפעמים זה הטירוף שהופך אותי חשוף מבקש עוד רגעים של מחשבה כל הקיץ שם איתה שני זרים אותה מיטה איך טעיתי כשזייפתי אהבה כבר שנים איני צוחק מתקרב ומתרחק מה יהיה בסוף אין איש יודע",
        createdAt: new Date(),
        updatedAt: new Date()
    },
    {
        id: 39,
        title: 'חמש מילים',
        artistId: 5,
        albumId: 5,
        youtubeLink: 'cre6qQDap3c',
        length: '03:24',
        trackNumber: 12,
        lyrics: "כמה עוד ימים כמה לילות איך אתה לא אומר לה  רק שלוש מילים מה יכול להיות אתה מבין מה קורה לה  נכון אתה זורק לפעמים ככה בין השורות  ז'תם איי לאב יו טאמו  אז למה קשה בעברית זו אותה משמעות  אני לא מבין מה נסגר פה  אולי כבר תקום ותפתח את הלב הגיע הזמן אתה לא חושב תלחש לה... בלעדייך לא תזרח עליי השמש  בשבילי את המחר היום ואמש כמה שאני אוהב אותך  תביני  לא יודע מי אני כבר בלעדייך  כמו תינוק תמיד צמא לשפתותייך  בואי ונאהב רק בעברית תקשיבי רציתי לומר לך חמש מילים  אני אוהב אותך עמוק בפנים כמה חודשים ים שבועות איך אתה לא אומר לה  רק שלוש מילים מה יכול להיות אתה מבין זה עושה לה  נכון אתה פוחד כמו אידיוט כך לשלוף רגשות  אולי תהיה קצת רומנטי  תפסיק לריב כבר עם עצמך זו אותה משמעות תתחיל להיות קצת סימפטי",
        createdAt: new Date(),
        updatedAt: new Date()
    },
    {
        id: 40,
        title: 'חוטים ומיקרופונים',
        artistId: 5,
        albumId: 5,
        youtubeLink: 'XQ5rG6Ty7MA',
        length: '03:28',
        trackNumber: 13,
        lyrics: "לא ביקשתי לי אורות גם לא קהל מה כבר רציתי לשיר לך שיר מתוך הלב זה כל מה שרציתי לא צריך במה חוטים ומיקרופונים לא ביקשתי לי תערוכה ברומא או פריז גם לא קריין שבקולו על אהבה יכריז רק ציור אחד רציתי לצייר לך זה מה שציפיתי מתוך העלטה רק את זוהרת שתיקות שרועמות איך את שוברת ואם יש מקום בשבילי בחייך אני כאן מחכה מסתובב כמו שיכור ברחובות בליבי כבר כתבתי את שמך לא נשאר לי מקום בחיי שאוכל בו לחיות מלבדך הרוח נעימה תמיד כשאת עוברת וכל דקה אהבה גוברת ואם נשמתך שבעה מבדידות אני כאן מחכה ברכות לא ביקשתי שושנים לא כינורות מה כבר רציתי רק לספר לך שאת כל מה שתמיד קיוויתי כל חיי אוהב אותך עד השמיים מכל התהומות תמיד למעלה ורק את מדליקה לי את הלילה ואם יש עוד חדר פנוי בליבך אני כאן מחכה",
        createdAt: new Date(),
        updatedAt: new Date()
    },
]